// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendClientLog(arg1:string,arg2:string):Promise<void>;

export function ApplyManagedAppConfigFiles(arg1:main.ManagedAppConfigApplyRequest):Promise<main.ManagedAppConfigApplyResult>;

export function ExtractChromeProfileTokens(arg1:main.ChromeProfileTokenRequest):Promise<main.ChromeProfileTokenResponse>;

export function ImportExtensionAccounts():Promise<main.ExtensionImportResult>;

export function ListDesktopLogFiles():Promise<main.DesktopLogSnapshot>;

export function PerformHttpRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function PerformHttpRequestRaw(arg1:string):Promise<string>;

export function ReadDesktopLogFile(arg1:string):Promise<main.DesktopLogContent>;

export function ReadManagedAppConfigFiles(arg1:Array<string>):Promise<main.ManagedAppConfigSnapshot>;
