// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendClientLog(arg1, arg2) {
  return window['go']['main']['App']['AppendClientLog'](arg1, arg2);
}

export function ApplyManagedAppConfigFiles(arg1) {
  return window['go']['main']['App']['ApplyManagedAppConfigFiles'](arg1);
}

export function ExtractChromeProfileTokens(arg1) {
  return window['go']['main']['App']['ExtractChromeProfileTokens'](arg1);
}

export function ImportExtensionAccounts() {
  return window['go']['main']['App']['ImportExtensionAccounts']();
}

export function ListDesktopLogFiles() {
  return window['go']['main']['App']['ListDesktopLogFiles']();
}

export function PerformHttpRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PerformHttpRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function PerformHttpRequestRaw(arg1) {
  return window['go']['main']['App']['PerformHttpRequestRaw'](arg1);
}

export function ReadDesktopLogFile(arg1) {
  return window['go']['main']['App']['ReadDesktopLogFile'](arg1);
}

export function ReadManagedAppConfigFiles(arg1) {
  return window['go']['main']['App']['ReadManagedAppConfigFiles'](arg1);
}
