// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendClientLog(arg1, arg2) {
  return window['go']['main']['App']['AppendClientLog'](arg1, arg2);
}

export function ApplyManagedAppConfigFiles(arg1) {
  return window['go']['main']['App']['ApplyManagedAppConfigFiles'](arg1);
}

export function CloseBridgeImportSession() {
  return window['go']['main']['App']['CloseBridgeImportSession']();
}

export function CloseDesktopProfileAssist(arg1) {
  return window['go']['main']['App']['CloseDesktopProfileAssist'](arg1);
}

export function CollapsePanel() {
  return window['go']['main']['App']['CollapsePanel']();
}

export function EnterSidebarMode() {
  return window['go']['main']['App']['EnterSidebarMode']();
}

export function ExitSidebarMode() {
  return window['go']['main']['App']['ExitSidebarMode']();
}

export function ExpandPanel() {
  return window['go']['main']['App']['ExpandPanel']();
}

export function ExtractChromeProfileTokens(arg1) {
  return window['go']['main']['App']['ExtractChromeProfileTokens'](arg1);
}

export function GetAdvancedProxyConfig() {
  return window['go']['main']['App']['GetAdvancedProxyConfig']();
}

export function GetAdvancedProxyConfigFilePath() {
  return window['go']['main']['App']['GetAdvancedProxyConfigFilePath']();
}

export function GetBridgeImportSnapshot() {
  return window['go']['main']['App']['GetBridgeImportSnapshot']();
}

export function GetChromeProfileExtractProgress() {
  return window['go']['main']['App']['GetChromeProfileExtractProgress']();
}

export function GetCircuitBreakerStats(arg1, arg2) {
  return window['go']['main']['App']['GetCircuitBreakerStats'](arg1, arg2);
}

export function GetFailoverQueue(arg1) {
  return window['go']['main']['App']['GetFailoverQueue'](arg1);
}

export function GetLaunchMode() {
  return window['go']['main']['App']['GetLaunchMode']();
}

export function GetLaunchRecordKey() {
  return window['go']['main']['App']['GetLaunchRecordKey']();
}

export function GetOutboundProxyConfig() {
  return window['go']['main']['App']['GetOutboundProxyConfig']();
}

export function GetPanelDockState() {
  return window['go']['main']['App']['GetPanelDockState']();
}

export function GetSidebarMode() {
  return window['go']['main']['App']['GetSidebarMode']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function HideToTrayPanel() {
  return window['go']['main']['App']['HideToTrayPanel']();
}

export function ImportExtensionAccounts() {
  return window['go']['main']['App']['ImportExtensionAccounts']();
}

export function ImportExtensionAccountsFromDir(arg1) {
  return window['go']['main']['App']['ImportExtensionAccountsFromDir'](arg1);
}

export function InitPanelWindow(arg1, arg2) {
  return window['go']['main']['App']['InitPanelWindow'](arg1, arg2);
}

export function ListDesktopLogFiles() {
  return window['go']['main']['App']['ListDesktopLogFiles']();
}

export function OpenBridgeScriptInstallPage() {
  return window['go']['main']['App']['OpenBridgeScriptInstallPage']();
}

export function OpenDesktopConfigWindow(arg1) {
  return window['go']['main']['App']['OpenDesktopConfigWindow'](arg1);
}

export function OpenDesktopProfileAssist(arg1) {
  return window['go']['main']['App']['OpenDesktopProfileAssist'](arg1);
}

export function OpenKeyEditor(arg1) {
  return window['go']['main']['App']['OpenKeyEditor'](arg1);
}

export function PackagePortableData(arg1) {
  return window['go']['main']['App']['PackagePortableData'](arg1);
}

export function PerformHttpRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PerformHttpRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function PerformHttpRequestRaw(arg1) {
  return window['go']['main']['App']['PerformHttpRequestRaw'](arg1);
}

export function PickExtensionImportDirectory() {
  return window['go']['main']['App']['PickExtensionImportDirectory']();
}

export function ReadDesktopLogFile(arg1) {
  return window['go']['main']['App']['ReadDesktopLogFile'](arg1);
}

export function ReadManagedAppConfigFiles(arg1) {
  return window['go']['main']['App']['ReadManagedAppConfigFiles'](arg1);
}

export function RequestMainWindowRestore() {
  return window['go']['main']['App']['RequestMainWindowRestore']();
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function ResetBridgeImportSession() {
  return window['go']['main']['App']['ResetBridgeImportSession']();
}

export function ResetCircuitBreaker(arg1, arg2) {
  return window['go']['main']['App']['ResetCircuitBreaker'](arg1, arg2);
}

export function ResetPanelExpandedWidth() {
  return window['go']['main']['App']['ResetPanelExpandedWidth']();
}

export function SetAdvancedProxyConfig(arg1) {
  return window['go']['main']['App']['SetAdvancedProxyConfig'](arg1);
}

export function SetFailoverQueue(arg1, arg2) {
  return window['go']['main']['App']['SetFailoverQueue'](arg1, arg2);
}

export function SetOutboundProxyConfig(arg1) {
  return window['go']['main']['App']['SetOutboundProxyConfig'](arg1);
}

export function SetPanelCollapsed(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPanelCollapsed'](arg1, arg2, arg3);
}

export function SetPanelExpandedWidth(arg1) {
  return window['go']['main']['App']['SetPanelExpandedWidth'](arg1);
}

export function SetPanelInteractionLocked(arg1) {
  return window['go']['main']['App']['SetPanelInteractionLocked'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartBridgeImportSession() {
  return window['go']['main']['App']['StartBridgeImportSession']();
}

export function ToggleSidebarMode() {
  return window['go']['main']['App']['ToggleSidebarMode']();
}

export function UnpackPortableData() {
  return window['go']['main']['App']['UnpackPortableData']();
}
