// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendClientLog(arg1:string,arg2:string):Promise<void>;

export function ApplyManagedAppConfigFiles(arg1:main.ManagedAppConfigApplyRequest):Promise<main.ManagedAppConfigApplyResult>;

export function CloseBridgeImportSession():Promise<main.BridgeImportSnapshot>;

export function CloseDesktopProfileAssist(arg1:Array<string>):Promise<Record<string, any>>;

export function CollapsePanel():Promise<void>;

export function EnterSidebarMode():Promise<void>;

export function ExitSidebarMode():Promise<void>;

export function ExpandPanel():Promise<void>;

export function ExportTextFile(arg1:string,arg2:string):Promise<string>;

export function ExtractChromeProfileTokens(arg1:main.ChromeProfileTokenRequest):Promise<main.ChromeProfileTokenResponse>;

export function GetAdvancedProxyConfig():Promise<main.AdvancedProxyConfig>;

export function GetAdvancedProxyConfigFilePath():Promise<string>;

export function GetAdvancedProxyRoutingSnapshot():Promise<main.AdvancedProxyRoutingSnapshot>;

export function GetBridgeImportSnapshot():Promise<main.BridgeImportSnapshot>;

export function GetChromeProfileExtractProgress():Promise<main.fetchKeysProgressSnapshot>;

export function GetCircuitBreakerStats(arg1:string,arg2:string):Promise<main.CircuitBreakerStats>;

export function GetFailoverQueue(arg1:string):Promise<Array<main.FailoverQueueItem>>;

export function GetLaunchMode():Promise<string>;

export function GetLaunchRecordKey():Promise<string>;

export function GetOutboundProxyConfig():Promise<main.OutboundProxyConfig>;

export function GetPanelDockState():Promise<string>;

export function GetPanelWindowBounds():Promise<main.sidebarWindowBounds>;

export function GetSidebarMode():Promise<boolean>;

export function HideToTray():Promise<void>;

export function HideToTrayPanel():Promise<void>;

export function ImportExtensionAccounts():Promise<main.ExtensionImportResult>;

export function ImportExtensionAccountsFromDir(arg1:string):Promise<main.ExtensionImportResult>;

export function InitPanelWindow(arg1:number,arg2:number):Promise<void>;

export function ListDesktopLogFiles():Promise<main.DesktopLogSnapshot>;

export function OpenBridgeScriptInstallPage():Promise<void>;

export function OpenDesktopConfigWindow(arg1:string):Promise<void>;

export function OpenDesktopProfileAssist(arg1:Array<main.desktopProfileAssistOpenRequest>):Promise<Record<string, any>>;

export function OpenKeyEditor(arg1:string):Promise<void>;

export function OpenManualSidebarPanel():Promise<void>;

export function PackagePortableData(arg1:string):Promise<main.PortableDataPackageResult>;

export function PerformHttpRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function PerformHttpRequestRaw(arg1:string):Promise<string>;

export function PickExtensionImportDirectory():Promise<string>;

export function ReadDesktopLogFile(arg1:string):Promise<main.DesktopLogContent>;

export function ReadManagedAppConfigFiles(arg1:Array<string>):Promise<main.ManagedAppConfigSnapshot>;

export function RequestMainWindowRestore():Promise<void>;

export function RequestQuit():Promise<void>;

export function ResetBridgeImportSession():Promise<main.BridgeImportSnapshot>;

export function ResetCircuitBreaker(arg1:string,arg2:string):Promise<boolean>;

export function ResetPanelExpandedWidth():Promise<void>;

export function SetAdvancedProxyConfig(arg1:main.AdvancedProxyConfig):Promise<main.AdvancedProxyConfig>;

export function SetFailoverQueue(arg1:string,arg2:Array<main.FailoverQueueItem>):Promise<Array<main.FailoverQueueItem>>;

export function SetOutboundProxyConfig(arg1:main.OutboundProxyConfig):Promise<main.OutboundProxyConfig>;

export function SetPanelCollapsed(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetPanelExpandedWidth(arg1:number):Promise<void>;

export function SetPanelInteractionLocked(arg1:boolean):Promise<void>;

export function SetPanelSuperMiniActive(arg1:boolean):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartBridgeImportSession():Promise<main.BridgeImportSnapshot>;

export function ToggleSidebarMode():Promise<void>;

export function UnpackPortableData():Promise<main.PortableDataUnpackResult>;
